{{- range .Values.activeDirectory.domainControllers }}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .name }}
  finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
  labels:
    vm.kubevirt.io/template: {{ $.Values.activeDirectory.vmTemplate.name }}
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.26.0
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: {{ .name }}-boot0
      spec:
        sourceRef:
          kind: DataSource
          {{- with $.Values.activeDirectory.vmTemplate.dataSource }}
          name: {{ .name }}
          namespace: {{ .namespace }}
          {{- end }}
        storage:
          storageClassName: {{ .storageClass | default "ocs-storagecluster-ceph-rbd-virtualization" }}
          resources:
            requests:
              storage: {{ .storageSize | default "100Gi" }}
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: {{ $.Values.activeDirectory.vmTemplate.operatingSystem }}
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: {{ .name }}
        kubevirt.io/size: medium
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/part-of: active-directory
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: {{ .cpuCores | default "4" }}
          threads: 1
        devices:
          features:
            acpi: {}
            apic: {}
            hyperv:
              reenlightenment: {}
              ipi: {}
              synic: {}
              synictimer:
                direct: {}
              spinlocks:
                spinlocks: 8191
              reset: {}
              relaxed: {}
              vpindex: {}
              runtime: {}
              tlbflush: {}
              frequencies: {}
              vapic: {}
            smm: {}
          firmware:
            bootloader:
              efi:
                secureBoot: true
          disks:
            - disk:
                bus: sata
              name: rootdisk
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - name: default
              masquerade: {}
              model: e1000e
              ports:
                - name: rdp
                  port: 3389
                  protocol: TCP
                - name: winrm
                  port: 5985
            - bridge: {}
              model: e1000e
              name: {{ .bridgeInterface.networkAttachmentDefinition }}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: {{ .memory | default "8Gi" }}
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: default/{{ .bridgeInterface.networkAttachmentDefinition }}
          name: {{ .bridgeInterface.networkAttachmentDefinition }}
      terminationGracePeriodSeconds: 3600
      volumes:
        - dataVolume:
            name: {{ .name }}-boot0
          name: rootdisk
{{- end }}