---

- name: Apply base config to all domain controllers
  hosts:
    - all
  tasks:
    - name: Ensure DNS servers are set to domain controllers
      ansible.windows.win_dns_client:
        adapter_names: "{{ bridge_interface.name }}"
        dns_servers: "{{ active_directory.domain_controller_ips }}"
    - name: Prevent registration of "internal" interface IP address
      ansible.windows.win_powershell:
        script: |
          [CmdletBinding()]
          param (
              [String]
              $InterfaceName
              )

          Write-Host "Turning off registration in DNS for interface $InterfaceName..."
          Set-DnsClient -InterfaceAlias $InterfaceName -RegisterThisConnectionsAddress $false
        parameters:
          InterfaceName: "{{ internal_interface.name }}"
    - name: Ensure SSDP/UPnP are started
      ansible.windows.win_service:
        name: "{{ item }}"
        state: started
        start_mode: auto
      loop:
        - SSDPSRV
        - upnphost
