---

- name: Link 62443-3-3 GPO to OU
  hosts:
    - all
  tasks:
    # Lazy, update to take vars in the future
    - name: Link GPO
      ansible.windows.win_shell: New-GPLink -Name "62443-3-3" -Target "OU=IndustrialSoftware,DC=basementinnovationcenter,DC=lcl"
      register: _link_ou
      changed_when:
        - "'already linked' not in _link_ou.stderr"
      failed_when:
        - "'already linked' not in _link_ou.stderr"
        - _link_ou.rc | int != 0
